apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: webapps
  template:
    metadata:
      labels:
        app: webapps
    spec:
      containers:
      - image: hemanthc12/tomcat
        name: tomcat
        ports:
        - containerPort: 8080