apiVersion: v1
kind: Pod
metadata:
  name: tomcat1
  labels:
    app: hello
spec:
<<<<<<< HEAD
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: webapps
  template:
    metadata:
      labels:
        app: webapps
    spec:
      containers:
      - image: hemanthc12/tomcat
        name: tomcat
        ports:
        - containerPort: 8080
=======
  containers:
    - name: tomcat
      image: hemanthc12/tomcat1
      ports:
        - containerPort: 8080
>>>>>>> 56b0acad6460555cb0cd72f4723672bac7e0213f
